# Generated by Django 4.1.3 on 2022-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonafide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Class', models.CharField(max_length=10, null=True)),
                ('Year', models.CharField(max_length=5, null=True)),
                ('reason', models.TextField(default='Reason')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
